spring:
  profiles:
    include:
      - db
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq:
  queue:
    email:
      name: email_queue
  exchange:
    email:
      name: email_exchange
  binding:
    email:
      name: email_routing_key

baku:
  app:
    jwtSecret: ======================DivAcademy=Spring===========================
    jwtExpirationMs: 86400000